# Generated by Django 4.0.3 on 2022-08-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='card',
            new_name='Product',
        ),
    ]
